# -*- coding: utf-8 -*-
"""kaggle_Submission_36Adaboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2z2fWkGw4cCd8MfFf0GqXxdS8QfJ-or

Importing the Libraries needed to execude AdaBoost Pipeline, decision tree classifier was later added as a base estimator for adaboost
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import roc_auc_score, precision_recall_curve, roc_curve

import warnings
warnings.filterwarnings('ignore')

"""Training and Test CSVs were loaded and shape was checked to ensure no data was lost from original files

"""

train = pd.read_csv('/content/fda_trainingset.csv')
test = pd.read_csv('/content/fda_testset.csv')
sample_submission = pd.read_csv('/content/sample_submission_FDA_file.csv')

print("Train shape:", train.shape)
print("Test shape:", test.shape)

"""EDA was done to visualise imbalance in the dataset, distribution of Y=1 is very low


"""

sns.countplot(x='Y', data=train)
plt.title('Target Variable Distribution')
plt.show()

print(train.describe())

"""Target and X variables were separated, Test IDs were separated to be included with final predictions to match sample submission file

"""

X = train.drop(columns=['Y'])
y = train['Y']
test_ids = test['ID']

"""Categorical columns were mentioned for One Hot Encoding, employment status, gender, collateral, dependents and matital status appeared as categorical columns. First 'unknowns' were filled in mission columns and then data was transformed. drop first step was performed to avoid multicollinearity by dropping one category from each feature


"""

cat_cols = [
    'employment_status_flag',
    'gender_flag',
    'collateral_flag',
    'dependents_count',
    'marital_status_flag'
]

for col in cat_cols:
    X[col] = X[col].fillna('Unknown')
    test[col] = test[col].fillna('Unknown')

ohe = OneHotEncoder(drop='first', sparse_output=False)
X_cat = ohe.fit_transform(X[cat_cols])
test_cat = ohe.transform(test[cat_cols])

X_cat = pd.DataFrame(X_cat, columns=ohe.get_feature_names_out(cat_cols))
test_cat = pd.DataFrame(test_cat, columns=ohe.get_feature_names_out(cat_cols))


X = X.drop(columns=cat_cols)
test = test.drop(columns=cat_cols)


X = pd.concat([X.reset_index(drop=True), X_cat.reset_index(drop=True)], axis=1)
test = pd.concat([test.reset_index(drop=True), test_cat.reset_index(drop=True)], axis=1)

"""Data was merged into full data to better apply preprocessing on thedataset and numerical columns were identified after which missing values were replaced by median. Median is used instead of mean to reduce impact of outliers which may be present in financial data

"""

full_data = pd.concat([X, test], axis=0).reset_index(drop=True)


num_cols = full_data.select_dtypes(include=['int64', 'float64']).columns.tolist()


for col in num_cols:
    full_data[col] = full_data[col].fillna(full_data[col].median())

"""Simple features were added such as sum of rows, the average of rows, the variance among rows and zeros in each row to check against each customer ID, no scaling was needed for adaboost so it was not done and then data was split back into original train and test."""

full_data['row_sum'] = full_data[num_cols].sum(axis=1)
full_data['row_mean'] = full_data[num_cols].mean(axis=1)
full_data['row_std'] = full_data[num_cols].std(axis=1)
full_data['row_zeros'] = (full_data[num_cols] == 0).sum(axis=1)


X_processed = full_data.iloc[:len(X)]
X_test_processed = full_data.iloc[len(X):]

X_balanced, y_balanced = X_processed, y

"""Decision Tree Classifier was added as it is the best functioning with adaboost, from previously done ADABOOST the estimators were increased to 1000 to upgrade model performance, previous testing of learning rate had been done from 0.1, 0.05 to 0.5 and 0.5 had showed best results"""

from sklearn.tree import DecisionTreeClassifier

base_tree = DecisionTreeClassifier(max_depth=2, min_samples_split=10)
best_model = AdaBoostClassifier(estimator=base_tree, n_estimators=1000, learning_rate=0.5, random_state=42)
best_model.fit(X_balanced, y_balanced)

"""Model results were used to generate predictions of the test set.

"""

y_test_preds_prob = best_model.predict_proba(X_test_processed)[:, 1]

"""Submission file was created and downloaded to submit CSV to Kaggle

"""

submission = pd.DataFrame({
    'ID': test_ids,
    'Y': y_test_preds_prob
})

submission.to_csv('Kaggle_submission_36Adaboost.csv', index=False)



from google.colab import files
files.download('Kaggle_submission_36Adaboost.csv')